name: Auto Release Extension

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Verify manifest version matches tag
        run: |
          MANIFEST_VERSION=$(node -p "require('./manifest.json').version")
          TAG_VERSION="${{ steps.get_version.outputs.VERSION }}"
          if [ "$MANIFEST_VERSION" != "$TAG_VERSION" ]; then
            echo "Error: manifest.json version ($MANIFEST_VERSION) does not match tag version ($TAG_VERSION)"
            exit 1
          fi
          echo "Version verified: $MANIFEST_VERSION"

      - name: Build extension
        run: npm run build:zip

      - name: Get commit messages since last tag
        id: changelog
        run: |
          PREV_TAG=$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1) 2>/dev/null || echo "")
          if [ -z "$PREV_TAG" ]; then
            CHANGELOG=$(git log --pretty=format:"- %s" HEAD)
          else
            CHANGELOG=$(git log --pretty=format:"- %s" ${PREV_TAG}..HEAD)
          fi
          echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: atlas-voice-extension.zip
          body: |
            ## Atlas Voice Extension v${{ steps.get_version.outputs.VERSION }}

            ### Changes
            ${{ steps.changelog.outputs.CHANGELOG }}

            ### Installation
            1. Download \`atlas-voice-extension.zip\`
            2. Extract the ZIP file
            3. Open Chrome and go to \`chrome://extensions\`
            4. Enable "Developer mode"
            5. Click "Load unpacked" and select the extracted folder

            ### Auto-Update
            If you already have Atlas installed, it will auto-update within 4 hours!

            ---
            Released: ${{ github.event.head_commit.timestamp }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify success
        run: |
          echo "✅ Release v${{ steps.get_version.outputs.VERSION }} created successfully!"
          echo "📦 ZIP uploaded: atlas-voice-extension.zip"
          echo "🔗 Release URL: https://github.com/${{ github.repository }}/releases/tag/v${{ steps.get_version.outputs.VERSION }}"
