name: Release Extension

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      working-directory: Desktop/atlas-voice-extension
      run: npm ci

    - name: Build extension
      working-directory: Desktop/atlas-voice-extension
      run: npm run build:zip

    - name: Get version from manifest
      working-directory: Desktop/atlas-voice-extension
      id: version
      run: |
        VERSION=$(node -p "require('./manifest.json').version")
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Atlas Voice Extension v${{ steps.version.outputs.version }}
        body: |
          ## Atlas Voice Extension v${{ steps.version.outputs.version }}

          ### 📦 Installation Instructions

          1. **Download the extension:**
             - Click the `atlas-voice-extension.zip` file below to download

          2. **Install in Chrome/Edge:**
             - Open `chrome://extensions/` (or `edge://extensions/`)
             - Enable "Developer mode" (toggle in top right)
             - Click "Load unpacked"
             - **Extract the ZIP file first**, then select the extracted folder
             - The extension should now appear in your browser

          3. **Setup:**
             - Pin the extension by clicking the puzzle piece icon → pin "Atlas Voice Panel"
             - Click the extension icon to open the side panel
             - Follow the setup instructions in the panel

          ### 🚀 Features
          - Voice AI assistant with OpenAI Realtime API
          - Side panel interface for easy access
          - Desktop automation capabilities
          - Screen capture and vision mode
          - Continuous conversation mode

          ### 📋 Requirements
          - Chrome or Edge browser
          - Microphone access for voice features
          - Server setup (see README for details)

          ---

          **Note:** This is a developer preview. Extract the ZIP file before loading into Chrome.
        files: Desktop/atlas-voice-extension/atlas-voice-extension.zip
        draft: false
        prerelease: false
